# Galaxy/Pulsar user setup
pulsar:
  user_name: galaxyumsa
  uid: 10456
  gid: 198
  group: galaxyumsa
  nfs_home: "brno11-elixir"
  nfs_prefix: pulsar-umsa

install_nfs_conda: false

# Put your Galaxy server's fully qualified domain name (FQDN) (or the FQDN of the RabbitMQ server) above.
rabbitmq_hostname: "galaxy-umsa.grid.cesnet.cz" # DEMON: Important to have proper FQDN of connected Galaxy server (or at least RabbitMQ server)
rabbitmq_vhost: "pulsar" # DEMON: must be the same rabbitmq vhost set for communication between Galaxy and Pulsar set on Galaxy side
rabbitmq_user: "{{ pulsar.user_name }}" # DEMON: must be user running connected Galaxy server
rabbitmq_port: 5671 # DEMON: must be port where to contact RabbitMQ server
