# define for all our hosts 
# expected to run ansible-playbook ... --limit HOSTNAME


nometapuppet:
  hosts:
    cloud255-47.cerit-sc.cz:		# ljochuv pulsar
      ansible_user: debian
    mu-pub-245-66.flt.openstack.cloud.e-infra.cz:
      ansible_user: debian
    pulsar-qa1.galaxy.cloud.e-infra.cz:
      ansible_user: debian
    pulsar-qa2.galaxy.cloud.e-infra.cz:
      ansible_user: debian

pulsarservers:
  hosts:
    cloud255-47.cerit-sc.cz:		# ljochuv pulsar
      ansible_user: debian
    pulsar-umsa.grid.cesnet.cz:
      ansible_user: root
    pulsar-re.grid.cesnet.cz:
      ansible_user: root
    pulsar-cz.grid.cesnet.cz:
      ansible_user: root
    pulsar-eu.grid.cesnet.cz:
      ansible_user: root
    mu-pub-245-66.flt.openstack.cloud.e-infra.cz:
      ansible_user: debian
    pulsar-qa1.galaxy.cloud.e-infra.cz:
      ansible_user: debian
    pulsar-qa2.galaxy.cloud.e-infra.cz:
      ansible_user: debian
