nometapuppet:
  hosts:
    pulsar-qa1.galaxy.cloud.e-infra.cz:
      ansible_user: debian
    pulsar-qa2.galaxy.cloud.e-infra.cz:
      ansible_user: debian

pulsarservers:
  hosts:
    pulsar-qa1.galaxy.cloud.e-infra.cz:
      ansible_user: debian
    pulsar-qa2.galaxy.cloud.e-infra.cz:
      ansible_user: debian
    pulsar-umsa.grid.cesnet.cz:
      ansible_user: debian
    pulsar-re.grid.cesnet.cz:
      ansible_user: root
    pulsar-cz.grid.cesnet.cz:
      ansible_user: debian
    pulsar-eu.grid.cesnet.cz:
      ansible_user: root
