# define for all our hosts 
# expected to run ansible-playbook ... --limit HOSTNAME


nometapuppet:
  hosts:
    cloud255-47.cerit-sc.cz:		# ljochuv pulsar
      ansible_user: debian

pulsarservers:
  hosts:
    cloud255-47.cerit-sc.cz:		# ljochuv pulsar
      ansible_user: debian

