- hosts: nometapuppet
  roles:
    - role: metacentrum.krbnfs
      become: yes

- hosts: pulsarservers
  pre_tasks:
    - group:
        name: "{{ pulsar.group }}"
        gid: "{{ pulsar.gid }}"
      become: yes
    - user:
        name: "{{ pulsar.user_name }}"
        uid: "{{ pulsar.uid }}"
        group: "{{ pulsar.group }}"
        shell: /bin/bash
      become: yes

    - name: Create pulsar root and persistent files folder
      ansible.builtin.file:
        path: "{{ pulsar_persistence_dir }}"
        state: directory
        recurse: yes
        #mode: 'a+x'
        owner: "{{ pulsar.user_name }}"
        group: "{{ pulsar.group }}"
      become: yes

  roles:
    - role: metacentrum.pulsar
      become: yes
    - role: galaxyproject.pulsar
      become: yes
      become_user: "{{ pulsar.user_name }}"

  post_tasks:
    - name: Apply recursive rsync changes in pulsar package
      ansible.posix.patch:
        src: "files/pulsar_repo/{{ pulsar_package_version }}/recursive_rsync.patch"
        basedir: "{{ pulsar_package_change_dir }}"
        backup: true
        strip: 1
      when: csnt_use_recursive_rsync
    - name: Restart pulsar service after change
      ansible.builtin.systemd:
        state: restarted
        name: "{{ pulsar_systemd_service_name }}"
      become: yes
      when: csnt_use_recursive_rsync

    - name: Create .drmaa folder in NFS home
      ansible.builtin.file:
        path: "{{ pulsar_network_homedir }}/.drmaa"
        state: directory
      become: yes
      become_user: "{{ pulsar.user_name }}"
    - name: Create cleanup_jobs dir
      ansible.builtin.file:
        path: "{{ pulsar_cleanup_dir }}"
        state: directory
        recurse: yes
        mode: 'a+x'
      become: yes
      become_user: "{{ pulsar.user_name }}"
    - name: Creates entry in crontab "tmpreaper call in staging dir"
      ansible.builtin.cron:
        name: "tmpreaper in staging dir"
        minute: "7"
        hour: "*/6"
        job: "/usr/sbin/tmpreaper --verbose=0 --showdeleted --all --mtime --mtime-dir --runtime=600 {{ pulsar_cleanup_delay }} {{ pulsar_staging_dir }} >> {{ pulsar_cleanup_dir }}/cleaning_pulsar_files.log"
      become: yes
      become_user: "{{ pulsar.user_name }}"
