- hosts: pulsarservers
  vars:
    # Golang
    golang_gopath: '/opt/workspace-go'
    # Singularity target version
    singularity_version: "3.7.4"
    singularity_go_path: "{{ golang_install_dir }}"
    # (Mini)conda
    #miniconda_prefix: /storage/brno11-elixir/home/galaxyelixir/pulsar-re/miniconda
    #miniconda_channels:
    #  - conda-forge
    #  - defaults
    #miniconda_base_env_packages:
    #  - mamba
    #miniconda_install_dir: /storage/brno11-elixir/home/galaxyelixir/pulsar-re
  vars_files:
    - group_vars/secret.yml
  pre_tasks:
    - name: Install some packages
      package:
        name:
          - build-essential
          - git
          - python3-dev
          - libcurl4-openssl-dev
          - libssl-dev
          - virtualenv
          - libgnutls28-dev
          - squashfs-tools # DEMON: needed by singularity roles
          - libpbspro-dev
        state: present
        update_cache: yes
      become: yes
    - name: Mount NFS volume to share job data with worker nodes
      ansible.posix.mount:
        src: "storage-{{ item }}.metacentrum.cz:/"
        path: "/auto/{{ item }}"
        opts: "sec=krb5i,proto=tcp,port=2049,intr"
        state: mounted
        fstype: nfs4
      become: yes
      loop:
         - brno11-elixir
         - praha5-elixir
  roles:
    - gantsign.golang
    - cyverse-ansible.singularity
    - galaxyproject.pulsar
    #- role: galaxyproject.miniconda
    #- role: andrewrothstein.miniconda
    #  become: true
    #  become_user: "{{ pulsar_user.name }}"
