- hosts: pulsarservers
  vars:
    # Golang
    golang_gopath: '/opt/workspace-go'
    # Singularity target version
    singularity_version: "3.7.4"
    singularity_go_path: "{{ golang_install_dir }}"
    # (Mini)conda
    #miniconda_prefix: /storage/brno11-elixir/home/galaxyelixir/pulsar-re/miniconda
    #miniconda_channels:
    #  - conda-forge
    #  - defaults
    #miniconda_base_env_packages:
    #  - mamba
    #miniconda_install_dir: /storage/brno11-elixir/home/galaxyelixir/pulsar-re
  vars_files:
    - group_vars/secret.yml
  pre_tasks:
    - group:
        name: "{{ pulsar_user.name }}"
        gid: "{{ pulsar_user.gid }}"
      become: yes
    - user:
        name: "{{ pulsar_user.name }}"
        uid: "{{ pulsar_user.uid }}"
        group: "{{ pulsar_user.name }}"
        shell: /bin/bash
      become: yes
    - name: Create pulsar root
      file:
        path: "{{ pulsar_root }}"
        state: directory
        owner: "{{ pulsar_user.name }}"
        group: "{{ pulsar_user.name }}"
      become: yes
        
  roles:
    - role: metacentrum.pulsar
      become: yes
#    - gantsign.golang
#    - cyverse-ansible.singularity
    - role: galaxyproject.pulsar
      become: yes
      become_user: "{{ pulsar_user.name }}"

#- role: galaxyproject.miniconda
#- role: andrewrothstein.miniconda

