- hosts: pulsarservers
  vars:
    #miniconda_prefix: /home/pulsar/conda
    #miniconda_channels:
    #  - conda-forge
    #  - anaconda
    #  - defaults
    #miniconda_base_env_packages:
    #  - mamba
  vars_files:
    - group_vars/secret.yml
  pre_tasks:
    - name: Install some packages
      package:
        name:
          - build-essential
          - git
          - python3-dev
          - libcurl4-openssl-dev
          - libssl-dev
          - virtualenv
          - libgnutls28-dev
          - squashfs-tools # DEMON: needed by singularity roles
        state: present
        update_cache: yes
      become: yes
  roles:
    #- role: galaxyproject.cvmfs
    #  become: yes
    - gantsign.golang
    - cyverse-ansible.singularity
    - galaxyproject.pulsar
    #- role: galaxyproject.miniconda
    #  become: true
