- src: galaxyproject.pulsar
  version: 1.0.8
- src: cyverse-ansible.singularity
  version: 048c4f178077d05c1e67ae8d9893809aac9ab3b7
- src: gantsign.golang
  version: 2.6.3
- src: galaxyproject.miniconda
  version: 0.3.1
#- src: andrewrothstein.miniconda #napicu, zla dokumentacia, nefunkcne premenne
