pulsar_user:
## Specific settings for pulsar-re (needs to be moved into host_vars foder
  name: galaxy-qa1
  uid:  11688
  gid: 10000
  group: meta
  nfs_home: "brno11-elixir"
  nfs_prefix: pulsar-dev
  
#rabbitmq_hostname: "galaxy-gxit.grid.cesnet.cz" # DEMON: Important to have proper FQDN of connected Galaxy server (or at least RabbitMQ server)
rabbitmq_hostname: "mu-pub-245-177.flt.openstack.cloud.e-infra.cz"
rabbitmq_vhost: "pulsar" # DEMON: must be the same rabbitmq vhost set for communication between Galaxy and Pulsar set on Galaxy side
rabbitmq_user: "{{ pulsar_user.name }}" # DEMON: must be user running connected Galaxy server
rabbitmq_port: 5671 # DEMON: must be port where to contact RabbitMQ server

#pulsar_data_dir: /storage/brno11-elixir/home/galaxyelixir/pulsar-gxit
#pulsar_data_dir: /storage/brno11-elixir/home/galaxyelixir/pulsar-dev
