- name: Install required standard packages
  package:
    name:
      - build-essential
      - git
      - gpg
      - python3-dev
      - libcurl4-openssl-dev
      - libssl-dev
      - virtualenv
      - libgnutls28-dev
      - squashfs-tools # DEMON: needed by singularity roles
      - krb5-user
      - nfs-common
      - rsync
      - tmpreaper
    state: present
    update_cache: yes

- name: Comment out SHOWWARNING line in tmpreaper config
  ansible.builtin.lineinfile:
    path: /etc/tmpreaper.conf
    regexp: "SHOWWARNING="
    state: absent

- name: Download DRMAA
  get_url:
    url: https://master.dl.sourceforge.net/project/pbspro-drmaa/pbs-drmaa/1.0/pbs-drmaa-{{ drmaa_version }}.tar.gz?viasf=1
    dest: /tmp/pbs-drmaa-{{ drmaa_version }}.tar.gz

- name: Install DRMAA
  shell: |
    cd /tmp
    rm -rf pbs-drmaa-{{ drmaa_version }}
    tar xzf pbs-drmaa-{{ drmaa_version }}.tar.gz
    cd pbs-drmaa-{{ drmaa_version }}
    ./configure --prefix /opt/drmaa
    make && make install

- name: KRB5 user keytab
  copy:
    content: "{{ krb5_user_keytab }}"
    dest: "/home/{{ pulsar_user.name }}/user.keytab"

- name: KRB5 user ticket
  command: "KRB5CCNAME=/tmp/krb5cc_{{ pulsar_user.name }} kinit -k -t /home/{{ pulsar_user.name }}/user.keytab {{ pulsar_user.name }}@META"
  become_user: '{{ pulsar_user.name }}'

- name: KRB5 ticket renewal
  cron:
    name: krb5 ticket
    minute: '1'
    hour: '*/6'
    job: 'KRB5CCNAME=/tmp/krb5cc_{{ pulsar_user.name }} kinit -k -t /home/{{ pulsar_user.name }}/user.keytab {{ pulsar_user.name }}@META'
    user: '{{ pulsar_user.name }}'

- name: KRB5 ticket creation on reboot
  cron:
    name: krb5 ticket on reboot
    special_time: reboot
    job: 'KRB5CCNAME=/tmp/krb5cc_{{ pulsar_user.name }} kinit -k -t /home/{{ pulsar_user.name }}/user.keytab {{ pulsar_user.name }}@META'
    user: '{{ pulsar_user.name }}'
