pulsar:
  user_name: galaxyelixir
  uid:  2469
  gid: 10145
  group: galaxyelixir
  nfs_home: "brno11-elixir"
  nfs_prefix: pulsar-re

miniconda_channels:
  - 'bioconda'
  - 'conda-forge'
  - 'petrnovak'
miniconda_prefix: "/storage/{{ pulsar.nfs_home }}/home/{{ pulsar.user_name }}/anaconda3"
miniconda_exec: "{{ miniconda_prefix }}/bin/mamba"

csnt_pulsar_cleanup_delay: "40d" # pulsar-re* need this to have over 30d
csnt_dependency_resolvers:
  - type: conda
    auto_init: true
    auto_install: true
    ensure_channels: "{{ miniconda_channels|join(',') }}"
    exec: "{{ miniconda_exec }}"
    prefix: "{{ miniconda_prefix }}"

# Put your Galaxy server's fully qualified domain name (FQDN) (or the FQDN of the RabbitMQ server) above.
rabbitmq_hostname: "galaxy-re.grid.cesnet.cz" # Important to have proper FQDN of connected Galaxy server (or at least RabbitMQ server)
rabbitmq_vhost: "pulsar2" # must be the same rabbitmq vhost set for communication between Galaxy and Pulsar set on Galaxy side
rabbitmq_user: "{{ pulsar.user_name }}" # must be user running connected Galaxy server
rabbitmq_port: 5671 # must be port where to contact RabbitMQ server
