pulsar:
  user_name: galaxy-qa1
  uid:  11688
  gid: 10000
  group: meta
  nfs_home: "brno11-elixir"
  nfs_prefix: pulsar-qa2

install_nfs_conda: false

rabbitmq_hostname: "galaxy-qa2.galaxy.cloud.e-infra.cz"
rabbitmq_vhost: "pulsar" # DEMON: must be the same rabbitmq vhost set for communication between Galaxy and Pulsar set on Galaxy side
rabbitmq_user: "{{ pulsar.user_name }}" # DEMON: must be user running connected Galaxy server
rabbitmq_port: 5671 # DEMON: must be port where to contact RabbitMQ server
