#! vim: ts=2 expandtab:

name: deploy-dev

# TODO: run automatically on push to main
on: [ workflow_dispatch ]

jobs:
  call-common:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v2
        
      - name: Call run-ansible-playbook action
        uses: ./.github/actions/run-ansible-playbook
        env:
          TARGET_HOSTNAME: pulsar-qa1.galaxy.cloud.e-infra.cz
          TARGET_USER: debian
          VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD_QA1 }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_QA1 }}
